
DROP TABLE IF EXISTS integrante;
DROP TABLE IF EXISTS usuarios;

CREATE TABLE IF NOT EXISTS integrante(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    fecha_incorporacion DATE NOT NULL,
    salario DOUBLE NOT NULL,
    pais VARCHAR(50) NOT NULL,
    rol VARCHAR (20) NOT NULL,
    especialidad VARCHAR (20),
    posicion VARCHAR (20),
    dorsal INT,
    altura DOUBLE,
    peso DOUBLE,
    goles INT,
    partidos_jugados INT,
    minutos_jugados INT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    updateAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    tipo VARCHAR (10)
    imagen VARCHAR (400) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios(
    username VARCHAR (30) PRIMARY KEY,
    password VARCHAR (30) PRIMARY KEY
)